export const students = [
  {
    Nama: 'Rafael Yonas Corneles Wongkar',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Makasili',
    'Tanggal Lahir': 1101081600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Saitama',
    'TGL KEBERANGKATAN': 1701907200000,
    'NAMA ORANG TUA': 'SELTY LIANDO',
    'NO HP ORANG TUA': 82393939252,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Julio Firman Iroth',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Ranoiapo',
    'Tanggal Lahir': 1120867200000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Kanagawa',
    'TGL KEBERANGKATAN': 1706140800000,
    'NAMA ORANG TUA': 'Imelda Rumengan',
    'NO HP ORANG TUA': 89675610942,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Andreas Hosea Rarung',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Surabaya',
    'Tanggal Lahir': 1116892800000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Kanagawa',
    'TGL KEBERANGKATAN': 1706140800000,
    'NAMA ORANG TUA': 'Janty julie pasla',
    'NO HP ORANG TUA': 895393314696,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Salmon Sahertian',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Sehati',
    'Tanggal Lahir': '19/07/200',
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '23 tahun',
    PENEMPATAN: null,
    'TGL KEBERANGKATAN': null,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Christofel Mokodompit',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Tanoyan Selatan',
    'Tanggal Lahir': 1068336000000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '20 tahun',
    PENEMPATAN: 'Kagawa',
    'TGL KEBERANGKATAN': 1710633600000,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Rexmundi Aquino Monintja',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Lolah Dua',
    'Tanggal Lahir': 1096934400000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Tokyo',
    'TGL KEBERANGKATAN': 1709251200000,
    'NAMA ORANG TUA': 'Elizabeth Rasuh',
    'NO HP ORANG TUA': '082195761750',
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Grivandi Jonathan Tuju',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Manembo',
    'Tanggal Lahir': 1120953600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Nagano',
    'TGL KEBERANGKATAN': 1709251200000,
    'NAMA ORANG TUA': 'MEINE KALANGIE',
    'NO HP ORANG TUA': '085396148843',
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Fernando Itcialdy Muhaling',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Balikpapan',
    'Tanggal Lahir': 1131840000000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Kanagawa',
    'TGL KEBERANGKATAN': '13 Maret 2024',
    'NAMA ORANG TUA': 'HANDRIS MUHALING',
    'NO HP ORANG TUA': '081527222196',
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Giovanni George Jacques Sondakh',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Mopolo',
    'Tanggal Lahir': 1118016000000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Kanagawa',
    'TGL KEBERANGKATAN': '13 Maret 2024',
    'NAMA ORANG TUA': 'YUNITA WALLA',
    'NO HP ORANG TUA': '085268360049',
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Rikardi Marcellino Porung',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Tinoor',
    'Tanggal Lahir': 1080259200000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Kanagawa',
    'TGL KEBERANGKATAN': 1709251200000,
    'NAMA ORANG TUA': 'JEFFRY BODY PORUNG',
    'NO HP ORANG TUA': '081393918850',
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Vickly Karolus Lintjewas',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Lolah',
    'Tanggal Lahir': 1131062400000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Kanagawa',
    'TGL KEBERANGKATAN': '07 April 2024',
    'NAMA ORANG TUA': 'YUFIAN LINTJEWAS',
    'NO HP ORANG TUA': '085757057225',
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Meylani Verly Salendu',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Raanan Baru',
    'Tanggal Lahir': 989884800000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '22 tahun',
    PENEMPATAN: 'Tokyo',
    'TGL KEBERANGKATAN': 1714003200000,
    'NAMA ORANG TUA': 'Hernie onibala',
    'NO HP ORANG TUA': ' 0821-8780-5091',
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'ANGELICA PROKLA TAROREH',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'TIMIKA',
    'Tanggal Lahir': 1103414400000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Fukushima',
    'TGL KEBERANGKATAN': 1713052800000,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'WENNI LUSHI WALANGITAN',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Lolah',
    'Tanggal Lahir': 1124236800000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Fukushima',
    'TGL KEBERANGKATAN': 1713052800000,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Nesiaku Gensonta Simonia Ering',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Tomohon',
    'Tanggal Lahir': 1072396800000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '20 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 1704067200000,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Regiovani Laheping',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Bitung',
    'Tanggal Lahir': 967939200000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '23 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 1704067200000,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Hosea Fabio Makalikis',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Tomohon',
    'Tanggal Lahir': 1099008000000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 1704067200000,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Gerry Kansil',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Mopolo',
    'Tanggal Lahir': 1094688000000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Kanagawa',
    'TGL KEBERANGKATAN': 1704067200000,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Gabriel Julian Runturambi',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Molompar',
    'Tanggal Lahir': 1026086400000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '21 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 1706745600000,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Ravael Aditya Paat',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Panah Jari',
    'Tanggal Lahir': 1126310400000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 1706745600000,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Stivano Jhonatan Naray',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Manado',
    'Tanggal Lahir': 1112745600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 1706745600000,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Albrian J. Liando',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Tomohon',
    'Tanggal Lahir': 1074816000000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '20 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 1706745600000,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Feighty Heru Miki Worung',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Manado',
    'Tanggal Lahir': 981417600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '22 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 1706745600000,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Alezandro Rafael Aube',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Manado',
    'Tanggal Lahir': 1103587200000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 1706745600000,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Klose Stevel Oroh',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Ranoiapo',
    'Tanggal Lahir': 1032220800000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '22 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 'Maret 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Juandri Antonius Wowor',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Raraatean',
    'Tanggal Lahir': 1105920000000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 'Maret 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Giovanni Imanuel Wongkar',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Kotamobagu',
    'Tanggal Lahir': 1133913600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 'Maret 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Christo Hart Joel Pungus',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Manado',
    'Tanggal Lahir': 915321600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '25 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 'Maret 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Teguh Dwiki Bimantara',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Manado',
    'Tanggal Lahir': 1110931200000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 'Maret 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Juandi Manope',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Kalasey',
    'Tanggal Lahir': 1054857600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '21 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 'Maret 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Evel Geres',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Inobonto 2',
    'Tanggal Lahir': 1095897600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '20 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 'Februari 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Luwuk Andrean Kalangi',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Surabaya',
    'Tanggal Lahir': 1099267200000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '20 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 'Februari 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'JEFNY EVALIN HALING',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Manado',
    'Tanggal Lahir': 772934400000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '30 tahun',
    PENEMPATAN: 'Kagawa',
    'TGL KEBERANGKATAN': '15 Februari 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'TIFFANY CLAUDIA PANGAW',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Jakarta',
    'Tanggal Lahir': 757382400000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '30 tahun',
    PENEMPATAN: 'Kagawa',
    'TGL KEBERANGKATAN': '15 Februari 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'RINNIE SENEWE',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Tomohon',
    'Tanggal Lahir': 882489600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '27 tahun',
    PENEMPATAN: 'Kagawa',
    'TGL KEBERANGKATAN': '15 Februari 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Joel Vabrian Pontoh',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Mopolo',
    'Tanggal Lahir': 1128470400000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Tokyo',
    'TGL KEBERANGKATAN': 1709251200000,
    'NAMA ORANG TUA': 'VANI PONTOH',
    'NO HP ORANG TUA': '081393918850',
    KETERANGAN: 'Waiting COE',
  },
  {
    Nama: 'Charol E A Lolowang',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Raanan Baru',
    'Tanggal Lahir': 1107820800000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Tokyo',
    'TGL KEBERANGKATAN': 1709251200000,
    'NAMA ORANG TUA': 'DJOIKE LOLOWANG',
    'NO HP ORANG TUA': '085314757170',
    KETERANGAN: 'Waiting COE',
  },
  {
    Nama: 'Mega Flora Reshinta Zeke',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Dumoga',
    'Tanggal Lahir': 1118707200000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Kochi',
    'TGL KEBERANGKATAN': 1714521600000,
    'NAMA ORANG TUA': 'MARTHEN ZEKE',
    'NO HP ORANG TUA': '085241005376',
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Yoga Samto Mickael Herson Sendeng',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Manado',
    'Tanggal Lahir': 1074297600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '20 tahun',
    PENEMPATAN: 'Niigata',
    'TGL KEBERANGKATAN': 1709251200000,
    'NAMA ORANG TUA': 'ROCHMANTY MARKASIM',
    'NO HP ORANG TUA': '0895-3962-17702',
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Alvaro Roger Roringpandey',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Mapanget',
    'Tanggal Lahir': 1107388800000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Niigata',
    'TGL KEBERANGKATAN': 1709251200000,
    'NAMA ORANG TUA': 'ALGEN RORINGPANDEY',
    'NO HP ORANG TUA': '085242793349',
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'George Ellya Viktor Kawengian',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Semarang',
    'Tanggal Lahir': 1071187200000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '20 tahun',
    PENEMPATAN: 'Niigata',
    'TGL KEBERANGKATAN': 1709251200000,
    'NAMA ORANG TUA': 'Refly kawengian Jumini',
    'NO HP ORANG TUA': '082398473204',
    KETERANGAN: 'JEPANG',
  },
  {
    Nama: 'Novri Manoppo',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Manado',
    'Tanggal Lahir': ' 06/11/1998',
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '26 tahun',
    PENEMPATAN: 'Fukuoka',
    'TGL KEBERANGKATAN': null,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'BERANGKAT JUNI 2024',
  },
  {
    Nama: 'Jufri Aer',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Man Gega',
    'Tanggal Lahir': 1055203200000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '21 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': null,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'BERANGKAT MEI 2024',
  },
  {
    Nama: 'Yunior Naftali Kaligis',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Manado',
    'Tanggal Lahir': 1118966400000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': null,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'BERANGKAT MEI 2024',
  },
  {
    Nama: 'Lowra Tesya Legi',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Motoling',
    'Tanggal Lahir': 1097712000000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '20 tahun',
    PENEMPATAN: 'Shizuoka',
    'TGL KEBERANGKATAN': null,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'BERANGKAT JUNI 2024',
  },
  {
    Nama: 'Krisna Aldo Rosaria Ambun',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Manado',
    'Tanggal Lahir': 985737600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '23 tahun',
    PENEMPATAN: 'Osaka',
    'TGL KEBERANGKATAN': 'Maret 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'BERANGKAT SEPTEMBER 2024',
  },
  {
    Nama: 'Kimberly Kaligis',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Manado',
    'Tanggal Lahir': 1003276800000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '22 tahun',
    PENEMPATAN: 'Chiba',
    'TGL KEBERANGKATAN': null,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'BERANGKAT SEPTEMBER 2024',
  },
  {
    Nama: 'Marsella Maria Sompotan',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Tomohon',
    'Tanggal Lahir': 1111536000000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Chiba',
    'TGL KEBERANGKATAN': null,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'BERANGKAT SEPTEMBER 2024',
  },
  {
    Nama: 'Mikha Tomponu',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Tombatu',
    'Tanggal Lahir': 984182400000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '23 tahun',
    PENEMPATAN: 'Chiba',
    'TGL KEBERANGKATAN': null,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'BERANGKAT SEPTEMBER 2024',
  },
  {
    Nama: 'Amaria Langkai',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Kumelembuai',
    'Tanggal Lahir': 1088035200000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '20 tahun',
    PENEMPATAN: 'Chiba',
    'TGL KEBERANGKATAN': null,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'BERANGKAT SEPTEMBER 2024',
  },
  {
    Nama: 'Stelicia Lela',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Tomposo Baru',
    'Tanggal Lahir': 1072310400000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '21 tahun',
    PENEMPATAN: 'Chiba',
    'TGL KEBERANGKATAN': null,
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'BERANGKAT SEPTEMBER 2024',
  },
  {
    Nama: 'LAURA ESTER VANIA',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Lamongan',
    'Tanggal Lahir': 1127865600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Nagasaki',
    'TGL KEBERANGKATAN': 'Mei 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'Menunggu Keberangkatan',
  },
  {
    Nama: 'MEALI SIFRA MACHAENAS',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Lobu',
    'Tanggal Lahir': 930700800000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '25 tahun',
    PENEMPATAN: 'Nagasaki',
    'TGL KEBERANGKATAN': 'Mei 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'Menunggu Keberangkatan',
  },
  {
    Nama: 'DEYANTI ANANDA MANANOHAS',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Bitung',
    'Tanggal Lahir': 1072569600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '21 tahun',
    PENEMPATAN: 'Fukuoka',
    'TGL KEBERANGKATAN': 'Mei 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'MENUNGGU COE',
  },
  {
    Nama: 'SHANIA ESTER RENATA SUMENDAP TORAR',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Manado',
    'Tanggal Lahir': 1078790400000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '18 tahun',
    PENEMPATAN: 'Nagasaki',
    'TGL KEBERANGKATAN': 'Agustus 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'MENUNGGU COE',
  },
  {
    Nama: 'TATIA SYELOMITA ANGKOUW',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Tondano',
    'Tanggal Lahir': 1132617600000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '19 tahun',
    PENEMPATAN: 'Nagasaki',
    'TGL KEBERANGKATAN': 'Agustus 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'MENUNGGU COE',
  },
  {
    Nama: 'LESTIANA SOSINGGIL',
    'Jenis Kelamin': null,
    'Tempat Lahir': 'Bebalang',
    'Tanggal Lahir': 1026000000000,
    Alamat: null,
    'Nomor Telepon': null,
    Email: null,
    'Pendidikan Terakhir': null,
    'Nama Sekolah': null,
    'Tahun Lulus': null,
    'Nomor Ijazah': null,
    NIK: null,
    Agama: null,
    'Lokasi Pelatihan': null,
    Umur: '22 tahun',
    PENEMPATAN: 'Nagasaki',
    'TGL KEBERANGKATAN': 'Mei 2024',
    'NAMA ORANG TUA': null,
    'NO HP ORANG TUA': null,
    KETERANGAN: 'MENUNGGU COE',
  },
];
